# Regressão Linear com Python


* Neste exercício irei construir uma regressão linear utilizando duas bibliotecas: Statsmodels e Scikit-Learn. Isso é o passo a passo que acompanhei de um vídeo do Mario Filho (https://www.youtube.com/watch?v=MPkNWpwxz7M). O intuito desse exercício é aprender como utilizar as bibliotecas e não fazem algo que realmente tenha utilidade preditiva.

In [63]:
#Bibliotecas
import pandas as pd
import numpy as np



In [64]:
#Importando o dataset
data = pd.read_csv("C:/Users/toazz/analise-dado/housing.csv")

In [65]:
data.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [66]:
dataset = data.dropna()

# Statsmodel


In [67]:
import statsmodels.api as sm
y = 'median_house_value'

In [68]:
dataset1 = dataset.drop('ocean_proximity', axis = 1)

In [69]:
dataset1.drop([y], axis = 1)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  
0           322.0       126.0         8.3252  
1          2401.0      1138.0         8.3014  
2           496.0       177.0         7.2574  
3           558.0       219.0         5.6431  
4           565.0       259.0         3.8462  
...           ...         ...            ...  
20635       845.0       330.0         1.5603  
20636       356.0       114.0         2.5568  
20637      1007.0       433.0         1.7000  
20638       741.0       349.0         1.8672  
20639      1387.0       530.0         2.3886  

[20433 rows x 8 columns]

In [70]:
modelo = sm.OLS(dataset1[y], dataset1.drop([y], axis =1))
res = modelo.fit()

In [71]:
res.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:     median_house_value   R-squared (uncentered):                   0.900
Model:                            OLS   Adj. R-squared (uncentered):              0.900
Method:                 Least Squares   F-statistic:                          2.300e+04
Date:                Mon, 28 Nov 2022   Prob (F-statistic):                        0.00
Time:                        08:49:56   Log-Likelihood:                     -2.5833e+05
No. Observations:               20433   AIC:                                  5.167e+05
Df Residuals:                   20425   BIC:                                  5.167e+05
Df Model:                           8                                                  
Covariance Type:            nonrobust                                                  
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
longitude          -2262.9266    108.739    -20.811      0.000   -2476.064   -2049.789
latitude           -8493.7869    344.069    -24.686      0.000   -9168.190   -7819.384
housing_median_age  1782.1508     45.199     39.429      0.000    1693.557    1870.744
total_rooms          -15.1143      0.845    -17.883      0.000     -16.771     -13.458
total_bedrooms        79.9151      7.434     10.750      0.000      65.344      94.486
population           -40.2138      1.167    -34.470      0.000     -42.501     -37.927
households           132.0915      7.967     16.581      0.000     116.476     147.707
median_income       4.555e+04    349.217    130.432      0.000    4.49e+04    4.62e+04
==============================================================================
Omnibus:                     4349.465   Durbin-Watson:                   0.970
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            14722.537
Skew:                           1.064   Prob(JB):                         0.00
Kurtosis:                       6.573   Cond. No.                     3.00e+03
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The condition number is large,  3e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [72]:
from sklearn.preprocessing import StandardScaler

In [115]:
#Com a normalizançção dos dados
X = dataset1.drop([y], axis =1)
scaler = StandardScaler()
normalized_X = scaler.fit_transform(X) #Note que não dividimos entre treino e teste pois para uma análise puramente estatística e não preditiva
#normalized_X = pd.DataFrame(normalized_X, columns=X.columns)#Fazemos isso pois o scaler retorna um numpy array
#normalized_X['intercept'] = 1

modelo = sm.OLS(dataset1[y], normalized_X)
res = modelo.fit()
print(res.summary())

                                 OLS Regression Results                                
Dep. Variable:     median_house_value   R-squared (uncentered):                   0.151
Model:                            OLS   Adj. R-squared (uncentered):              0.151
Method:                 Least Squares   F-statistic:                              454.9
Date:                Mon, 28 Nov 2022   Prob (F-statistic):                        0.00
Time:                        09:55:41   Log-Likelihood:                     -2.8018e+05
No. Observations:               20433   AIC:                                  5.604e+05
Df Residuals:                   20425   BIC:                                  5.604e+05
Df Model:                           8                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

In [74]:
dataset1[y].info()

<class 'pandas.core.series.Series'>
Int64Index: 20433 entries, 0 to 20639
Series name: median_house_value
Non-Null Count  Dtype  
--------------  -----  
20433 non-null  float64
dtypes: float64(1)
memory usage: 319.3 KB


In [75]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20433 entries, 0 to 20639
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20433 non-null  float64
 1   latitude            20433 non-null  float64
 2   housing_median_age  20433 non-null  float64
 3   total_rooms         20433 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20433 non-null  float64
 6   households          20433 non-null  float64
 7   median_income       20433 non-null  float64
dtypes: float64(8)
memory usage: 1.4 MB


# Scikit-Learn

In [91]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [95]:
dataset1.shape

(20433, 9)

In [100]:
Xtrain, Xval, ytrain, yval = train_test_split(X, dataset1[y], test_size = 0.3, random_state=0)
print(Xtrain.shape, Xval.shape, ytrain.shape, yval.shape)

modelo = LinearRegression(normalize = True)
modelo.fit(Xtrain, ytrain)

p = modelo.predict(Xval)

(14303, 8) (6130, 8) (14303,) (6130,)


C:\Users\toazz\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  warnings.warn(


In [101]:
p

array([184057.49030818, 162251.63875749, 115551.99346549, ...,
       115042.1546709 ,  63404.94656033, 216050.4594768 ])

In [103]:
from sklearn.metrics import mean_squared_error
mean_squared_error(yval, p)

4822825850.315343

In [105]:
modelo.coef_

array([-4.31673744e+04, -4.27754787e+04,  1.16208214e+03, -7.34374126e+00,
        1.10281353e+02, -3.55333374e+01,  3.92350849e+01,  3.99358596e+04])

# Scikit-learn Standardizado


* Fazendo a normalização dos dados de treino e de validação no Scikit-learn para ver se há alguma mudança. Veja que os coeficientes lá no final são bem parecidos com os encontrados quando fizemos nos Statsmodels.

In [110]:
Xtrain, Xval, ytrain, yval = train_test_split(X, dataset1[y], test_size = 0.3, random_state=0)
print(Xtrain.shape, Xval.shape, ytrain.shape, yval.shape)

scaler = StandardScaler()
Xtrain_scaled = scaler.fit_transform(Xtrain)
Xval_scaled = scaler.transform(Xval)

modelo = LinearRegression(normalize = False)
modelo.fit(Xtrain_scaled, ytrain)

p = modelo.predict(Xval)

(14303, 8) (6130, 8) (14303,) (6130,)


C:\Users\toazz\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:148: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2. Please leave the normalize parameter to its default value to silence this warning. The default behavior of this estimator is to not do any normalization. If normalization is needed please use sklearn.preprocessing.StandardScaler instead.
  warnings.warn(
C:\Users\toazz\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


In [111]:
p

array([-54779465.19784961, -97946759.80515878, -63940160.07799666, ...,
       -66057102.50987881, -39446084.28287017, -55364189.38008267])

In [112]:
from sklearn.metrics import mean_squared_error
mean_squared_error(yval, p)

6476238424792325.0

In [113]:
modelo.coef_

array([-86500.94096776, -91331.23903145,  14643.42216538, -16110.21212865,
        46649.87412717, -40726.53456531,  15077.13125811,  76110.1720303 ])